// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.network.dns.dns_query_single_label", false);
user_pref("app.normandy.user_id", "c47d7275-b6c5-4717-95f3-35f4f87dbf49");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1613981197);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1613981238);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1613981177);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1613981317);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1613981226);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7592);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1613981166);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{43d1b549-cb22-404b-8342-02a37d6f28d4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1613981214838");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1613983034838");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1613981186422");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1614002786422");
user_pref("browser.search.region", "AM");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1613981182");
user_pref("browser.slowStartup.averageTime", 12825);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20201110001500");
user_pref("browser.startup.homepage_override.mstone", "78.5.0");
user_pref("browser.startup.lastColdStartupCheck", 1613981174);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1613981180471");
user_pref("distribution.iniFile.exists.appversion", "78.5.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "bdf5b53b3d9d4982ac755a01b2f94167");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.5.0");
user_pref("extensions.lastPlatformVersion", "78.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"16a4a575-3f10-4975-8b1d-fdbfb6252848\",\"formautofill@mozilla.org\":\"be22b0d7-ce1d-4763-b621-3933dba9042a\",\"screenshots@mozilla.org\":\"f3643ada-43ab-4a47-961d-f87c2c8cc2f2\",\"webcompat-reporter@mozilla.org\":\"a1f7e22d-6731-4808-80a3-4b83be2e27bf\",\"webcompat@mozilla.org\":\"1779798b-2bd3-4a10-a2d2-235035cba83d\",\"default-theme@mozilla.org\":\"5a94efa5-803b-422c-985a-55414d7a5636\",\"google@search.mozilla.org\":\"a3605d54-4457-434f-8bf7-f01ed12f7e40\",\"amazondotcom@search.mozilla.org\":\"8f67b4a9-00fa-4bc8-8568-a0b0c53b1ed9\",\"wikipedia@search.mozilla.org\":\"2ac039b6-4a7b-48cc-84d8-ed8526e3fad7\",\"bing@search.mozilla.org\":\"7ff06c3f-d5dc-4247-8346-90405b1dbeae\",\"ddg@search.mozilla.org\":\"b48d3cd5-3c56-4019-9b06-db1664dfd63f\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20201110001500");
user_pref("media.gmp-manager.lastCheck", 1613981232);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1613981234);
user_pref("security.remote_settings.intermediates.checked", 1613981234);
user_pref("security.sandbox.content.tempDirSuffix", "695bd8e2-acd6-4dd2-9ad9-2b71867b3a0f");
user_pref("security.sandbox.plugin.tempDirSuffix", "a7d86a44-55c4-41be-9723-f2a47408e8c4");
user_pref("services.blocklist.addons-mlbf.checked", 1613981234);
user_pref("services.blocklist.gfx.checked", 1613981234);
user_pref("services.blocklist.pinning.checked", 1613981234);
user_pref("services.blocklist.plugins.checked", 1613981234);
user_pref("services.settings.clock_skew_seconds", -2);
user_pref("services.settings.last_etag", "\"1613980717109\"");
user_pref("services.settings.last_update_seconds", 1613981234);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1613981234);
user_pref("services.settings.main.cfr-fxa.last_check", 1613981234);
user_pref("services.settings.main.cfr.last_check", 1613981234);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1613981234);
user_pref("services.settings.main.hijack-blocklists.last_check", 1613981234);
user_pref("services.settings.main.language-dictionaries.last_check", 1613981234);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1613981234);
user_pref("services.settings.main.public-suffix-list.last_check", 1613981234);
user_pref("services.settings.main.search-config.last_check", 1613981234);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1613981234);
user_pref("services.settings.main.sites-classification.last_check", 1613981234);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1613981234);
user_pref("services.settings.main.whats-new-panel.last_check", 1613981234);
user_pref("services.settings.security.onecrl.checked", 1613981234);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1613981160);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20201110001500");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
